version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10  # Use Python 3.10 Docker image
    steps:
      - checkout  # Check out the code from the repository
      
      - run:
          name: Update and Upgrade System
          command: sudo apt-get update

      - run:
          name: Upgrade pip
          command: python3 -m pip install --upgrade pip
      
      - run:
          name: Install Dependencies
          command: python3 -m pip install telebot flask pymongo aiohttp

      - run:
          name: Run Script
          command: chmod +x * && python3 RAGNAROK.py
